export type State = {
  slug: string;
  name: string;
  abbr: string;
  expanded: boolean;
  adultLimitPct: number; // % of FPL for adults
  childLimitPct: number; // % of FPL for children
  pregnantLimitPct: number; // % of FPL for pregnant women
  adultMonthly1: string; // monthly income limit household of 1
  adultMonthly3: string; // monthly income limit household of 3
  childMonthly1: string;
  childMonthly3: string;
  applyUrl: string;
  phone: string;
  notes: string;
};

export const STATES: State[] = [
  {
    slug: "alabama",
    name: "Alabama",
    abbr: "AL",
    expanded: false,
    adultLimitPct: 18,
    childLimitPct: 141,
    pregnantLimitPct: 146,
    adultMonthly1: "~$226/mo",
    adultMonthly3: "~$383/mo",
    childMonthly1: "~$1,772/mo",
    childMonthly3: "~$3,037/mo",
    applyUrl: "https://myalhome.org",
    phone: "1-800-362-1504",
    notes: "Alabama did not expand Medicaid. Single adults without children or a disability generally do not qualify.",
  },
  {
    slug: "alaska",
    name: "Alaska",
    abbr: "AK",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 175,
    pregnantLimitPct: 175,
    adultMonthly1: "~$2,523/mo",
    adultMonthly3: "~$4,327/mo",
    childMonthly1: "~$3,199/mo",
    childMonthly3: "~$5,485/mo",
    applyUrl: "https://www.mybenefits.alaska.gov",
    phone: "1-800-478-7778",
    notes: "Alaska expanded Medicaid under the ACA. Most low-income adults qualify.",
  },
  {
    slug: "arizona",
    name: "Arizona",
    abbr: "AZ",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 161,
    pregnantLimitPct: 161,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,022/mo",
    childMonthly3: "~$3,467/mo",
    applyUrl: "https://healthearizonaplus.gov",
    phone: "1-855-HEA-PLUS",
    notes: "Arizona expanded Medicaid (called AHCCCS). Most low-income adults qualify.",
  },
  {
    slug: "arkansas",
    name: "Arkansas",
    abbr: "AR",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 211,
    pregnantLimitPct: 211,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,650/mo",
    childMonthly3: "~$4,543/mo",
    applyUrl: "https://www.access.arkansas.gov",
    phone: "1-855-372-1084",
    notes: "Arkansas expanded Medicaid under the ACA.",
  },
  {
    slug: "california",
    name: "California",
    abbr: "CA",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 266,
    pregnantLimitPct: 213,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,341/mo",
    childMonthly3: "~$5,729/mo",
    applyUrl: "https://www.coveredca.com",
    phone: "1-800-300-1506",
    notes: "California (Medi-Cal) expanded Medicaid and now covers all income-eligible adults regardless of immigration status.",
  },
  {
    slug: "colorado",
    name: "Colorado",
    abbr: "CO",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 260,
    pregnantLimitPct: 195,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,266/mo",
    childMonthly3: "~$5,599/mo",
    applyUrl: "https://coloradopeak.secure.force.com",
    phone: "1-800-221-3943",
    notes: "Colorado expanded Medicaid. Most low-income adults qualify.",
  },
  {
    slug: "connecticut",
    name: "Connecticut",
    abbr: "CT",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 201,
    pregnantLimitPct: 258,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,524/mo",
    childMonthly3: "~$4,329/mo",
    applyUrl: "https://www.access.ct.gov",
    phone: "1-855-805-4325",
    notes: "Connecticut expanded Medicaid under the ACA.",
  },
  {
    slug: "delaware",
    name: "Delaware",
    abbr: "DE",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 212,
    pregnantLimitPct: 212,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,662/mo",
    childMonthly3: "~$4,565/mo",
    applyUrl: "https://www.benefits.delaware.gov",
    phone: "1-866-843-7212",
    notes: "Delaware expanded Medicaid under the ACA.",
  },
  {
    slug: "florida",
    name: "Florida",
    abbr: "FL",
    expanded: false,
    adultLimitPct: 26,
    childLimitPct: 210,
    pregnantLimitPct: 196,
    adultMonthly1: "~$326/mo",
    adultMonthly3: "~$559/mo",
    childMonthly1: "~$2,637/mo",
    childMonthly3: "~$4,522/mo",
    applyUrl: "https://www.myflorida.com/accessflorida",
    phone: "1-866-762-2237",
    notes: "Florida did not expand Medicaid. Single adults without children or a disability face very low income limits.",
  },
  {
    slug: "georgia",
    name: "Georgia",
    abbr: "GA",
    expanded: false,
    adultLimitPct: 35,
    childLimitPct: 211,
    pregnantLimitPct: 220,
    adultMonthly1: "~$439/mo",
    adultMonthly3: "~$754/mo",
    childMonthly1: "~$2,650/mo",
    childMonthly3: "~$4,543/mo",
    applyUrl: "https://gateway.ga.gov",
    phone: "1-877-423-4746",
    notes: "Georgia did not fully expand Medicaid but has a limited expansion program called Georgia Pathways requiring work requirements.",
  },
  {
    slug: "hawaii",
    name: "Hawaii",
    abbr: "HI",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 314,
    pregnantLimitPct: 196,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,942/mo",
    childMonthly3: "~$6,759/mo",
    applyUrl: "https://medquest.hawaii.gov",
    phone: "1-800-316-8005",
    notes: "Hawaii expanded Medicaid and has one of the most generous children's programs in the country.",
  },
  {
    slug: "idaho",
    name: "Idaho",
    abbr: "ID",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 190,
    pregnantLimitPct: 138,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,386/mo",
    childMonthly3: "~$4,091/mo",
    applyUrl: "https://healthandwelfare.idaho.gov",
    phone: "1-877-456-1233",
    notes: "Idaho expanded Medicaid in 2020 via ballot initiative.",
  },
  {
    slug: "illinois",
    name: "Illinois",
    abbr: "IL",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 313,
    pregnantLimitPct: 213,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,930/mo",
    childMonthly3: "~$6,738/mo",
    applyUrl: "https://abe.illinois.gov",
    phone: "1-800-843-6154",
    notes: "Illinois expanded Medicaid and has a very generous children's program.",
  },
  {
    slug: "indiana",
    name: "Indiana",
    abbr: "IN",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 208,
    pregnantLimitPct: 208,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,612/mo",
    childMonthly3: "~$4,480/mo",
    applyUrl: "https://www.in.gov/fssa/ompp",
    phone: "1-800-403-0864",
    notes: "Indiana expanded Medicaid through HIP 2.0, which has monthly contributions for some enrollees.",
  },
  {
    slug: "iowa",
    name: "Iowa",
    abbr: "IA",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 302,
    pregnantLimitPct: 375,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,792/mo",
    childMonthly3: "~$6,503/mo",
    applyUrl: "https://dhs.iowa.gov/ime/members/medicaid-a-to-z/ia-health-link",
    phone: "1-800-338-8366",
    notes: "Iowa expanded Medicaid and has a very generous pregnant women's program.",
  },
  {
    slug: "kansas",
    name: "Kansas",
    abbr: "KS",
    expanded: false,
    adultLimitPct: 38,
    childLimitPct: 238,
    pregnantLimitPct: 171,
    adultMonthly1: "~$477/mo",
    adultMonthly3: "~$818/mo",
    childMonthly1: "~$2,989/mo",
    childMonthly3: "~$5,126/mo",
    applyUrl: "https://www.kancare.ks.gov",
    phone: "1-800-792-4884",
    notes: "Kansas did not expand Medicaid. Income limits for adults are very low.",
  },
  {
    slug: "kentucky",
    name: "Kentucky",
    abbr: "KY",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 218,
    pregnantLimitPct: 213,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,737/mo",
    childMonthly3: "~$4,693/mo",
    applyUrl: "https://kynect.ky.gov",
    phone: "1-855-459-6328",
    notes: "Kentucky expanded Medicaid and has seen dramatic reductions in its uninsured rate.",
  },
  {
    slug: "louisiana",
    name: "Louisiana",
    abbr: "LA",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 212,
    pregnantLimitPct: 212,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,662/mo",
    childMonthly3: "~$4,565/mo",
    applyUrl: "https://ldh.la.gov/medicaid",
    phone: "1-888-342-6207",
    notes: "Louisiana expanded Medicaid in 2016.",
  },
  {
    slug: "maine",
    name: "Maine",
    abbr: "ME",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 208,
    pregnantLimitPct: 208,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,612/mo",
    childMonthly3: "~$4,480/mo",
    applyUrl: "https://www.maine.gov/dhhs/ofi/programs-services/mainecare",
    phone: "1-800-977-6740",
    notes: "Maine expanded Medicaid via ballot initiative in 2017.",
  },
  {
    slug: "maryland",
    name: "Maryland",
    abbr: "MD",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 317,
    pregnantLimitPct: 264,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,979/mo",
    childMonthly3: "~$6,823/mo",
    applyUrl: "https://www.marylandhealthconnection.gov",
    phone: "1-855-642-8572",
    notes: "Maryland expanded Medicaid and has one of the most generous children's programs.",
  },
  {
    slug: "massachusetts",
    name: "Massachusetts",
    abbr: "MA",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 300,
    pregnantLimitPct: 200,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,767/mo",
    childMonthly3: "~$6,460/mo",
    applyUrl: "https://www.mass.gov/masshealth",
    phone: "1-800-841-2900",
    notes: "Massachusetts expanded Medicaid and has had near-universal coverage since 2006.",
  },
  {
    slug: "michigan",
    name: "Michigan",
    abbr: "MI",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 212,
    pregnantLimitPct: 212,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,662/mo",
    childMonthly3: "~$4,565/mo",
    applyUrl: "https://www.michigan.gov/mdhhs/doing-business/providers/medicaid",
    phone: "1-800-642-3195",
    notes: "Michigan expanded Medicaid in 2014.",
  },
  {
    slug: "minnesota",
    name: "Minnesota",
    abbr: "MN",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 283,
    pregnantLimitPct: 278,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,554/mo",
    childMonthly3: "~$6,095/mo",
    applyUrl: "https://mn.gov/dhs/people-we-serve/adults/health-care/health-care-programs/programs-and-services/medical-assistance.jsp",
    phone: "1-800-657-3739",
    notes: "Minnesota expanded Medicaid and has a very generous program.",
  },
  {
    slug: "mississippi",
    name: "Mississippi",
    abbr: "MS",
    expanded: false,
    adultLimitPct: 27,
    childLimitPct: 209,
    pregnantLimitPct: 194,
    adultMonthly1: "~$339/mo",
    adultMonthly3: "~$582/mo",
    childMonthly1: "~$2,625/mo",
    childMonthly3: "~$4,502/mo",
    applyUrl: "https://www.ms.gov/dhs/home/",
    phone: "1-800-421-2408",
    notes: "Mississippi did not expand Medicaid and has some of the most restrictive eligibility rules in the country.",
  },
  {
    slug: "missouri",
    name: "Missouri",
    abbr: "MO",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 300,
    pregnantLimitPct: 196,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,767/mo",
    childMonthly3: "~$6,460/mo",
    applyUrl: "https://mydss.mo.gov",
    phone: "1-855-373-4636",
    notes: "Missouri expanded Medicaid via ballot initiative in 2020.",
  },
  {
    slug: "montana",
    name: "Montana",
    abbr: "MT",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 261,
    pregnantLimitPct: 154,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,279/mo",
    childMonthly3: "~$5,623/mo",
    applyUrl: "https://dphhs.mt.gov/MontanaHealthcarePrograms/Medicaid",
    phone: "1-800-362-8312",
    notes: "Montana expanded Medicaid in 2016.",
  },
  {
    slug: "nebraska",
    name: "Nebraska",
    abbr: "NE",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 212,
    pregnantLimitPct: 194,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,662/mo",
    childMonthly3: "~$4,565/mo",
    applyUrl: "https://www.nebraska.gov/apps-dhhs-nebraska-access-online",
    phone: "1-855-632-7633",
    notes: "Nebraska expanded Medicaid via ballot initiative in 2018.",
  },
  {
    slug: "nevada",
    name: "Nevada",
    abbr: "NV",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 200,
    pregnantLimitPct: 200,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,511/mo",
    childMonthly3: "~$4,308/mo",
    applyUrl: "https://www.medicaid.nv.gov",
    phone: "1-800-992-0900",
    notes: "Nevada expanded Medicaid in 2014.",
  },
  {
    slug: "new-hampshire",
    name: "New Hampshire",
    abbr: "NH",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 318,
    pregnantLimitPct: 196,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,993/mo",
    childMonthly3: "~$6,847/mo",
    applyUrl: "https://www.dhhs.nh.gov/programs-services/medicaid",
    phone: "1-844-275-3447",
    notes: "New Hampshire expanded Medicaid in 2014.",
  },
  {
    slug: "new-jersey",
    name: "New Jersey",
    abbr: "NJ",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 355,
    pregnantLimitPct: 205,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$4,458/mo",
    childMonthly3: "~$7,644/mo",
    applyUrl: "https://www.nj.gov/humanservices/dmahs/home/",
    phone: "1-800-356-1561",
    notes: "New Jersey expanded Medicaid and has one of the most generous children's programs in the country.",
  },
  {
    slug: "new-mexico",
    name: "New Mexico",
    abbr: "NM",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 240,
    pregnantLimitPct: 250,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,014/mo",
    childMonthly3: "~$5,168/mo",
    applyUrl: "https://www.hsd.state.nm.us/lookingforassistance/medicaid.aspx",
    phone: "1-888-997-2583",
    notes: "New Mexico expanded Medicaid and covers most low-income adults.",
  },
  {
    slug: "new-york",
    name: "New York",
    abbr: "NY",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 400,
    pregnantLimitPct: 223,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$5,023/mo",
    childMonthly3: "~$8,611/mo",
    applyUrl: "https://www.health.ny.gov/health_care/medicaid/",
    phone: "1-800-541-2831",
    notes: "New York expanded Medicaid and has one of the most comprehensive programs in the country.",
  },
  {
    slug: "north-carolina",
    name: "North Carolina",
    abbr: "NC",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 216,
    pregnantLimitPct: 196,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,712/mo",
    childMonthly3: "~$4,651/mo",
    applyUrl: "https://www.ncdhhs.gov/divisions/health-benefits",
    phone: "1-888-245-0179",
    notes: "North Carolina expanded Medicaid in December 2023.",
  },
  {
    slug: "north-dakota",
    name: "North Dakota",
    abbr: "ND",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 175,
    pregnantLimitPct: 175,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,198/mo",
    childMonthly3: "~$3,769/mo",
    applyUrl: "https://www.nd.gov/dhs/services/medicalserv/medicaid/",
    phone: "1-800-755-2604",
    notes: "North Dakota expanded Medicaid in 2014.",
  },
  {
    slug: "ohio",
    name: "Ohio",
    abbr: "OH",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 206,
    pregnantLimitPct: 206,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,587/mo",
    childMonthly3: "~$4,437/mo",
    applyUrl: "https://benefits.ohio.gov",
    phone: "1-800-324-8680",
    notes: "Ohio expanded Medicaid in 2014.",
  },
  {
    slug: "oklahoma",
    name: "Oklahoma",
    abbr: "OK",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 205,
    pregnantLimitPct: 205,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,574/mo",
    childMonthly3: "~$4,415/mo",
    applyUrl: "https://www.ohca.state.ok.us",
    phone: "1-800-987-7767",
    notes: "Oklahoma expanded Medicaid via ballot initiative in 2021.",
  },
  {
    slug: "oregon",
    name: "Oregon",
    abbr: "OR",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 300,
    pregnantLimitPct: 185,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,767/mo",
    childMonthly3: "~$6,460/mo",
    applyUrl: "https://healthcare.oregon.gov/Pages/index.aspx",
    phone: "1-800-699-9075",
    notes: "Oregon expanded Medicaid and has a very comprehensive program called Oregon Health Plan.",
  },
  {
    slug: "pennsylvania",
    name: "Pennsylvania",
    abbr: "PA",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 314,
    pregnantLimitPct: 215,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,942/mo",
    childMonthly3: "~$6,759/mo",
    applyUrl: "https://www.compass.state.pa.us",
    phone: "1-800-692-7462",
    notes: "Pennsylvania expanded Medicaid in 2015.",
  },
  {
    slug: "rhode-island",
    name: "Rhode Island",
    abbr: "RI",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 261,
    pregnantLimitPct: 253,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,279/mo",
    childMonthly3: "~$5,623/mo",
    applyUrl: "https://www.eohhs.ri.gov/consumer-information/medicaid",
    phone: "1-855-MY-RIDHS",
    notes: "Rhode Island expanded Medicaid in 2014.",
  },
  {
    slug: "south-carolina",
    name: "South Carolina",
    abbr: "SC",
    expanded: false,
    adultLimitPct: 67,
    childLimitPct: 208,
    pregnantLimitPct: 194,
    adultMonthly1: "~$841/mo",
    adultMonthly3: "~$1,442/mo",
    childMonthly1: "~$2,612/mo",
    childMonthly3: "~$4,480/mo",
    applyUrl: "https://www.scdhhs.gov",
    phone: "1-888-549-0820",
    notes: "South Carolina did not expand Medicaid. Income limits for adults are very low.",
  },
  {
    slug: "south-dakota",
    name: "South Dakota",
    abbr: "SD",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 207,
    pregnantLimitPct: 133,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,599/mo",
    childMonthly3: "~$4,459/mo",
    applyUrl: "https://dss.sd.gov/medicaid/",
    phone: "1-800-452-7691",
    notes: "South Dakota expanded Medicaid via ballot initiative in 2022.",
  },
  {
    slug: "tennessee",
    name: "Tennessee",
    abbr: "TN",
    expanded: false,
    adultLimitPct: 95,
    childLimitPct: 250,
    pregnantLimitPct: 195,
    adultMonthly1: "~$1,193/mo",
    adultMonthly3: "~$2,046/mo",
    childMonthly1: "~$3,140/mo",
    childMonthly3: "~$5,384/mo",
    applyUrl: "https://www.tn.gov/tenncare/members-applicants.html",
    phone: "1-800-342-3145",
    notes: "Tennessee did not expand Medicaid. Parents may qualify at higher limits but single adults face strict restrictions.",
  },
  {
    slug: "texas",
    name: "Texas",
    abbr: "TX",
    expanded: false,
    adultLimitPct: 15,
    childLimitPct: 198,
    pregnantLimitPct: 198,
    adultMonthly1: "~$188/mo",
    adultMonthly3: "~$323/mo",
    childMonthly1: "~$2,486/mo",
    childMonthly3: "~$4,264/mo",
    applyUrl: "https://www.yourtexasbenefits.com",
    phone: "2-1-1",
    notes: "Texas did not expand Medicaid and has some of the strictest eligibility rules in the country. Single adults without children generally do not qualify.",
  },
  {
    slug: "utah",
    name: "Utah",
    abbr: "UT",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 200,
    pregnantLimitPct: 139,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,511/mo",
    childMonthly3: "~$4,308/mo",
    applyUrl: "https://health.utah.gov/medicaid",
    phone: "1-877-543-7669",
    notes: "Utah expanded Medicaid via ballot initiative in 2019.",
  },
  {
    slug: "vermont",
    name: "Vermont",
    abbr: "VT",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 312,
    pregnantLimitPct: 208,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,917/mo",
    childMonthly3: "~$6,717/mo",
    applyUrl: "https://dvha.vermont.gov/members",
    phone: "1-800-250-8427",
    notes: "Vermont expanded Medicaid and has near-universal healthcare coverage.",
  },
  {
    slug: "virginia",
    name: "Virginia",
    abbr: "VA",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 200,
    pregnantLimitPct: 200,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$2,511/mo",
    childMonthly3: "~$4,308/mo",
    applyUrl: "https://www.coverva.org",
    phone: "1-833-523-1691",
    notes: "Virginia expanded Medicaid in 2019.",
  },
  {
    slug: "washington",
    name: "Washington",
    abbr: "WA",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 312,
    pregnantLimitPct: 193,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,917/mo",
    childMonthly3: "~$6,717/mo",
    applyUrl: "https://www.hca.wa.gov/apple-health",
    phone: "1-800-562-3022",
    notes: "Washington expanded Medicaid (called Apple Health) and covers most low-income adults.",
  },
  {
    slug: "west-virginia",
    name: "West Virginia",
    abbr: "WV",
    expanded: true,
    adultLimitPct: 138,
    childLimitPct: 305,
    pregnantLimitPct: 175,
    adultMonthly1: "~$1,732/mo",
    adultMonthly3: "~$2,972/mo",
    childMonthly1: "~$3,830/mo",
    childMonthly3: "~$6,567/mo",
    applyUrl: "https://dhhr.wv.gov/bcf/Services/pages/Medicaid.aspx",
    phone: "1-877-716-1212",
    notes: "West Virginia expanded Medicaid in 2014.",
  },
  {
    slug: "wisconsin",
    name: "Wisconsin",
    abbr: "WI",
    expanded: false,
    adultLimitPct: 100,
    childLimitPct: 306,
    pregnantLimitPct: 306,
    adultMonthly1: "~$1,255/mo",
    adultMonthly3: "~$2,152/mo",
    childMonthly1: "~$3,842/mo",
    childMonthly3: "~$6,590/mo",
    applyUrl: "https://www.dhs.wisconsin.gov/badgercareplus/index.htm",
    phone: "1-800-362-3002",
    notes: "Wisconsin did not expand Medicaid but covers adults up to 100% FPL through BadgerCare Plus.",
  },
  {
    slug: "wyoming",
    name: "Wyoming",
    abbr: "WY",
    expanded: false,
    adultLimitPct: 54,
    childLimitPct: 200,
    pregnantLimitPct: 154,
    adultMonthly1: "~$678/mo",
    adultMonthly3: "~$1,163/mo",
    childMonthly1: "~$2,511/mo",
    childMonthly3: "~$4,308/mo",
    applyUrl: "https://health.wyo.gov/healthcarefin/medicaid/",
    phone: "1-307-777-6964",
    notes: "Wyoming did not expand Medicaid. Income limits for adults are very low.",
  },
  {
    slug: "washington-dc",
    name: "Washington, DC",
    abbr: "DC",
    expanded: true,
    adultLimitPct: 215,
    childLimitPct: 319,
    pregnantLimitPct: 319,
    adultMonthly1: "~$2,699/mo",
    adultMonthly3: "~$4,629/mo",
    childMonthly1: "~$4,005/mo",
    childMonthly3: "~$6,869/mo",
    applyUrl: "https://dchealth.dc.gov/service/medicaid",
    phone: "1-855-532-5465",
    notes: "Washington DC has the most generous Medicaid program in the country, covering adults up to 215% FPL.",
  },
];

export function getStateBySlug(slug: string): State | undefined {
  return STATES.find((s) => s.slug === slug);
}

export function getAllSlugs(): string[] {
  return STATES.map((s) => s.slug);
}
